version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: submanageai-mongo
    ports:
      - "27017:27017"
    volumes:
      - submanageai-db:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: submanageai-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

volumes:
  submanageai-db:


